Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Parameters:
  NameParam:    
    Type: String      
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function    
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      FunctionName: 
        Ref: NameParam
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
            